### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by mikehenriquezf** [charanpy/ReactNative-InstagramClone#2]
Hello @charanpy and thank you for showing us a lot with this amazing project. Im kind of new with React Native, and i wonder where can i find the script to configure the mail settings, because im getting a error while register  that is error sending email. Also im really interested in see the Post feature in action, is there a way to load that screen instead the splash screen? cannot find where to modify that.

thank you! 

:)

**Comment by charanpy** [comment]
Hey, @mikehenriquezf  thank you for your kind words. I am currently not working on this project because it takes a lot of time to launch the react-native app in the expo and android studio as I have a low-end laptop.

For registration, I have a working code in the backend where you can fill up your Gmail settings and get it working 
https://github.com/charanpy/instagram-clone-API/blob/main/controllers/authController.js. Here I am using nodemon and Gmail as services for sending the email.

You can get rid of the splash screen (https://github.com/charanpy/ReactNative-InstagramClone/blob/main/Navigation/Navigation.js). At the end of the file, you can find createAppContainer where you can remove the splash screen.

I have implemented loading functionality in the Instagram clone using react(web app) which may help you. (https://github.com/charanpy/Instagram-react). Check out App. container file where you can find useAuth hook which uses loader and redirects to page based on user auth state.
